# Generated by Django 3.0.5 on 2021-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('bio', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
