# Generated by Django 3.0.5 on 2021-01-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
